GET http://localhost:8000/atributos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJub21icmUiOiJURVNUMiIsImlkIjozLCJtYWlsIjoidGVzdEBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2NDE4OTQ2MDIsImV4cCI6MTY0MjQ5OTQwMn0.Y63A4nUmZajp7L4h2w8oZMHEnOvbLCukvehXG_6Um5A
